[package]
name = "nanoserde-derive"
version = "0.1.10"
authors = ["Makepad <info@makepad.nl>", "Fedor <not.fl3@gmail.com>"]
edition = "2018"
description = "For of makepad-tinyserde derive without any external dependencies"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
